// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20220405180805_AddSeeds")]
    partial class AddSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Eletronicos",
                            Description = "Notebook ideapad S145 com melhor custo benêficios",
                            ImageUrl = "//",
                            Name = "Notebook 14'",
                            Price = 6500.59m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Eletronicos",
                            Description = "Notebook ideapad S145 com melhor custo benêficios",
                            ImageUrl = "//",
                            Name = "Notebook 14'",
                            Price = 6500.59m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Eletronicos",
                            Description = "Notebook ideapad S145 com melhor custo benêficios",
                            ImageUrl = "//",
                            Name = "Notebook 14'",
                            Price = 6500.59m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Eletronicos",
                            Description = "Notebook ideapad S145 com melhor custo benêficios",
                            ImageUrl = "//",
                            Name = "Notebook 14'",
                            Price = 6500.59m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Eletronicos",
                            Description = "Notebook ideapad S145 com melhor custo benêficios",
                            ImageUrl = "//",
                            Name = "Notebook 14'",
                            Price = 6500.59m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Eletronicos",
                            Description = "Notebook ideapad S145 com melhor custo benêficios",
                            ImageUrl = "//",
                            Name = "Notebook 14'",
                            Price = 6500.59m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Eletronicos",
                            Description = "Notebook ideapad S145 com melhor custo benêficios",
                            ImageUrl = "//",
                            Name = "Notebook 14'",
                            Price = 6500.59m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Eletronicos",
                            Description = "Notebook ideapad S145 com melhor custo benêficios",
                            ImageUrl = "//",
                            Name = "Notebook 14'",
                            Price = 6500.59m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Eletronicos",
                            Description = "Notebook ideapad S145 com melhor custo benêficios",
                            ImageUrl = "//",
                            Name = "Notebook 14'",
                            Price = 6500.59m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Eletronicos",
                            Description = "Notebook ideapad S145 com melhor custo benêficios",
                            ImageUrl = "//",
                            Name = "Notebook 14'",
                            Price = 6500.59m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
